development:
    adapter: mysql2
    database: xmcrm_development
    pool: 5
    timeout: 5000
    encoding: utf8
    reconnect: false 
    username: root
    password: 1q2w3e4r
    host: localhost

test: &test
    adapter: mysql2
    database: xmcrm_test
    pool: 5
    timeout: 5000
    encoding: utf8
    reconnect: false 
    username: root
    password: 1q2w3e4r
    host: localhost

production:
    adapter: mysql2
    database: xmcrm_production
    pool: 5
    timeout: 5000
    encoding: utf8
    reconnect: false 
    username: root
    password: 1q2w3e4r
    host: localhost
