require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ChannelInfosController do

  # This should return the minimal set of attributes required to create a valid
  # ChannelInfo. As you add validations to ChannelInfo, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ChannelInfosController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all channel_infos as @channel_infos" do
      channel_info = ChannelInfo.create! valid_attributes
      get :index, {}, valid_session
      assigns(:channel_infos).should eq([channel_info])
    end
  end

  describe "GET show" do
    it "assigns the requested channel_info as @channel_info" do
      channel_info = ChannelInfo.create! valid_attributes
      get :show, {:id => channel_info.to_param}, valid_session
      assigns(:channel_info).should eq(channel_info)
    end
  end

  describe "GET new" do
    it "assigns a new channel_info as @channel_info" do
      get :new, {}, valid_session
      assigns(:channel_info).should be_a_new(ChannelInfo)
    end
  end

  describe "GET edit" do
    it "assigns the requested channel_info as @channel_info" do
      channel_info = ChannelInfo.create! valid_attributes
      get :edit, {:id => channel_info.to_param}, valid_session
      assigns(:channel_info).should eq(channel_info)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ChannelInfo" do
        expect {
          post :create, {:channel_info => valid_attributes}, valid_session
        }.to change(ChannelInfo, :count).by(1)
      end

      it "assigns a newly created channel_info as @channel_info" do
        post :create, {:channel_info => valid_attributes}, valid_session
        assigns(:channel_info).should be_a(ChannelInfo)
        assigns(:channel_info).should be_persisted
      end

      it "redirects to the created channel_info" do
        post :create, {:channel_info => valid_attributes}, valid_session
        response.should redirect_to(ChannelInfo.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved channel_info as @channel_info" do
        # Trigger the behavior that occurs when invalid params are submitted
        ChannelInfo.any_instance.stub(:save).and_return(false)
        post :create, {:channel_info => {}}, valid_session
        assigns(:channel_info).should be_a_new(ChannelInfo)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ChannelInfo.any_instance.stub(:save).and_return(false)
        post :create, {:channel_info => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested channel_info" do
        channel_info = ChannelInfo.create! valid_attributes
        # Assuming there are no other channel_infos in the database, this
        # specifies that the ChannelInfo created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ChannelInfo.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => channel_info.to_param, :channel_info => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested channel_info as @channel_info" do
        channel_info = ChannelInfo.create! valid_attributes
        put :update, {:id => channel_info.to_param, :channel_info => valid_attributes}, valid_session
        assigns(:channel_info).should eq(channel_info)
      end

      it "redirects to the channel_info" do
        channel_info = ChannelInfo.create! valid_attributes
        put :update, {:id => channel_info.to_param, :channel_info => valid_attributes}, valid_session
        response.should redirect_to(channel_info)
      end
    end

    describe "with invalid params" do
      it "assigns the channel_info as @channel_info" do
        channel_info = ChannelInfo.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ChannelInfo.any_instance.stub(:save).and_return(false)
        put :update, {:id => channel_info.to_param, :channel_info => {}}, valid_session
        assigns(:channel_info).should eq(channel_info)
      end

      it "re-renders the 'edit' template" do
        channel_info = ChannelInfo.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ChannelInfo.any_instance.stub(:save).and_return(false)
        put :update, {:id => channel_info.to_param, :channel_info => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested channel_info" do
      channel_info = ChannelInfo.create! valid_attributes
      expect {
        delete :destroy, {:id => channel_info.to_param}, valid_session
      }.to change(ChannelInfo, :count).by(-1)
    end

    it "redirects to the channel_infos list" do
      channel_info = ChannelInfo.create! valid_attributes
      delete :destroy, {:id => channel_info.to_param}, valid_session
      response.should redirect_to(channel_infos_url)
    end
  end

end
