require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ExamDetailsController do

  # This should return the minimal set of attributes required to create a valid
  # ExamDetail. As you add validations to ExamDetail, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ExamDetailsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all exam_details as @exam_details" do
      exam_detail = ExamDetail.create! valid_attributes
      get :index, {}, valid_session
      assigns(:exam_details).should eq([exam_detail])
    end
  end

  describe "GET show" do
    it "assigns the requested exam_detail as @exam_detail" do
      exam_detail = ExamDetail.create! valid_attributes
      get :show, {:id => exam_detail.to_param}, valid_session
      assigns(:exam_detail).should eq(exam_detail)
    end
  end

  describe "GET new" do
    it "assigns a new exam_detail as @exam_detail" do
      get :new, {}, valid_session
      assigns(:exam_detail).should be_a_new(ExamDetail)
    end
  end

  describe "GET edit" do
    it "assigns the requested exam_detail as @exam_detail" do
      exam_detail = ExamDetail.create! valid_attributes
      get :edit, {:id => exam_detail.to_param}, valid_session
      assigns(:exam_detail).should eq(exam_detail)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ExamDetail" do
        expect {
          post :create, {:exam_detail => valid_attributes}, valid_session
        }.to change(ExamDetail, :count).by(1)
      end

      it "assigns a newly created exam_detail as @exam_detail" do
        post :create, {:exam_detail => valid_attributes}, valid_session
        assigns(:exam_detail).should be_a(ExamDetail)
        assigns(:exam_detail).should be_persisted
      end

      it "redirects to the created exam_detail" do
        post :create, {:exam_detail => valid_attributes}, valid_session
        response.should redirect_to(ExamDetail.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved exam_detail as @exam_detail" do
        # Trigger the behavior that occurs when invalid params are submitted
        ExamDetail.any_instance.stub(:save).and_return(false)
        post :create, {:exam_detail => {}}, valid_session
        assigns(:exam_detail).should be_a_new(ExamDetail)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ExamDetail.any_instance.stub(:save).and_return(false)
        post :create, {:exam_detail => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested exam_detail" do
        exam_detail = ExamDetail.create! valid_attributes
        # Assuming there are no other exam_details in the database, this
        # specifies that the ExamDetail created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ExamDetail.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => exam_detail.to_param, :exam_detail => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested exam_detail as @exam_detail" do
        exam_detail = ExamDetail.create! valid_attributes
        put :update, {:id => exam_detail.to_param, :exam_detail => valid_attributes}, valid_session
        assigns(:exam_detail).should eq(exam_detail)
      end

      it "redirects to the exam_detail" do
        exam_detail = ExamDetail.create! valid_attributes
        put :update, {:id => exam_detail.to_param, :exam_detail => valid_attributes}, valid_session
        response.should redirect_to(exam_detail)
      end
    end

    describe "with invalid params" do
      it "assigns the exam_detail as @exam_detail" do
        exam_detail = ExamDetail.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ExamDetail.any_instance.stub(:save).and_return(false)
        put :update, {:id => exam_detail.to_param, :exam_detail => {}}, valid_session
        assigns(:exam_detail).should eq(exam_detail)
      end

      it "re-renders the 'edit' template" do
        exam_detail = ExamDetail.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ExamDetail.any_instance.stub(:save).and_return(false)
        put :update, {:id => exam_detail.to_param, :exam_detail => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested exam_detail" do
      exam_detail = ExamDetail.create! valid_attributes
      expect {
        delete :destroy, {:id => exam_detail.to_param}, valid_session
      }.to change(ExamDetail, :count).by(-1)
    end

    it "redirects to the exam_details list" do
      exam_detail = ExamDetail.create! valid_attributes
      delete :destroy, {:id => exam_detail.to_param}, valid_session
      response.should redirect_to(exam_details_url)
    end
  end

end
