require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe InfoNotesController do

  # This should return the minimal set of attributes required to create a valid
  # InfoNote. As you add validations to InfoNote, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # InfoNotesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all info_notes as @info_notes" do
      info_note = InfoNote.create! valid_attributes
      get :index, {}, valid_session
      assigns(:info_notes).should eq([info_note])
    end
  end

  describe "GET show" do
    it "assigns the requested info_note as @info_note" do
      info_note = InfoNote.create! valid_attributes
      get :show, {:id => info_note.to_param}, valid_session
      assigns(:info_note).should eq(info_note)
    end
  end

  describe "GET new" do
    it "assigns a new info_note as @info_note" do
      get :new, {}, valid_session
      assigns(:info_note).should be_a_new(InfoNote)
    end
  end

  describe "GET edit" do
    it "assigns the requested info_note as @info_note" do
      info_note = InfoNote.create! valid_attributes
      get :edit, {:id => info_note.to_param}, valid_session
      assigns(:info_note).should eq(info_note)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new InfoNote" do
        expect {
          post :create, {:info_note => valid_attributes}, valid_session
        }.to change(InfoNote, :count).by(1)
      end

      it "assigns a newly created info_note as @info_note" do
        post :create, {:info_note => valid_attributes}, valid_session
        assigns(:info_note).should be_a(InfoNote)
        assigns(:info_note).should be_persisted
      end

      it "redirects to the created info_note" do
        post :create, {:info_note => valid_attributes}, valid_session
        response.should redirect_to(InfoNote.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved info_note as @info_note" do
        # Trigger the behavior that occurs when invalid params are submitted
        InfoNote.any_instance.stub(:save).and_return(false)
        post :create, {:info_note => {}}, valid_session
        assigns(:info_note).should be_a_new(InfoNote)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        InfoNote.any_instance.stub(:save).and_return(false)
        post :create, {:info_note => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested info_note" do
        info_note = InfoNote.create! valid_attributes
        # Assuming there are no other info_notes in the database, this
        # specifies that the InfoNote created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        InfoNote.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => info_note.to_param, :info_note => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested info_note as @info_note" do
        info_note = InfoNote.create! valid_attributes
        put :update, {:id => info_note.to_param, :info_note => valid_attributes}, valid_session
        assigns(:info_note).should eq(info_note)
      end

      it "redirects to the info_note" do
        info_note = InfoNote.create! valid_attributes
        put :update, {:id => info_note.to_param, :info_note => valid_attributes}, valid_session
        response.should redirect_to(info_note)
      end
    end

    describe "with invalid params" do
      it "assigns the info_note as @info_note" do
        info_note = InfoNote.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        InfoNote.any_instance.stub(:save).and_return(false)
        put :update, {:id => info_note.to_param, :info_note => {}}, valid_session
        assigns(:info_note).should eq(info_note)
      end

      it "re-renders the 'edit' template" do
        info_note = InfoNote.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        InfoNote.any_instance.stub(:save).and_return(false)
        put :update, {:id => info_note.to_param, :info_note => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested info_note" do
      info_note = InfoNote.create! valid_attributes
      expect {
        delete :destroy, {:id => info_note.to_param}, valid_session
      }.to change(InfoNote, :count).by(-1)
    end

    it "redirects to the info_notes list" do
      info_note = InfoNote.create! valid_attributes
      delete :destroy, {:id => info_note.to_param}, valid_session
      response.should redirect_to(info_notes_url)
    end
  end

end
