require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe NsfmsController do

  # This should return the minimal set of attributes required to create a valid
  # Nsfm. As you add validations to Nsfm, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # NsfmsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all nsfms as @nsfms" do
      nsfm = Nsfm.create! valid_attributes
      get :index, {}, valid_session
      assigns(:nsfms).should eq([nsfm])
    end
  end

  describe "GET show" do
    it "assigns the requested nsfm as @nsfm" do
      nsfm = Nsfm.create! valid_attributes
      get :show, {:id => nsfm.to_param}, valid_session
      assigns(:nsfm).should eq(nsfm)
    end
  end

  describe "GET new" do
    it "assigns a new nsfm as @nsfm" do
      get :new, {}, valid_session
      assigns(:nsfm).should be_a_new(Nsfm)
    end
  end

  describe "GET edit" do
    it "assigns the requested nsfm as @nsfm" do
      nsfm = Nsfm.create! valid_attributes
      get :edit, {:id => nsfm.to_param}, valid_session
      assigns(:nsfm).should eq(nsfm)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Nsfm" do
        expect {
          post :create, {:nsfm => valid_attributes}, valid_session
        }.to change(Nsfm, :count).by(1)
      end

      it "assigns a newly created nsfm as @nsfm" do
        post :create, {:nsfm => valid_attributes}, valid_session
        assigns(:nsfm).should be_a(Nsfm)
        assigns(:nsfm).should be_persisted
      end

      it "redirects to the created nsfm" do
        post :create, {:nsfm => valid_attributes}, valid_session
        response.should redirect_to(Nsfm.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved nsfm as @nsfm" do
        # Trigger the behavior that occurs when invalid params are submitted
        Nsfm.any_instance.stub(:save).and_return(false)
        post :create, {:nsfm => {}}, valid_session
        assigns(:nsfm).should be_a_new(Nsfm)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Nsfm.any_instance.stub(:save).and_return(false)
        post :create, {:nsfm => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested nsfm" do
        nsfm = Nsfm.create! valid_attributes
        # Assuming there are no other nsfms in the database, this
        # specifies that the Nsfm created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Nsfm.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => nsfm.to_param, :nsfm => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested nsfm as @nsfm" do
        nsfm = Nsfm.create! valid_attributes
        put :update, {:id => nsfm.to_param, :nsfm => valid_attributes}, valid_session
        assigns(:nsfm).should eq(nsfm)
      end

      it "redirects to the nsfm" do
        nsfm = Nsfm.create! valid_attributes
        put :update, {:id => nsfm.to_param, :nsfm => valid_attributes}, valid_session
        response.should redirect_to(nsfm)
      end
    end

    describe "with invalid params" do
      it "assigns the nsfm as @nsfm" do
        nsfm = Nsfm.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Nsfm.any_instance.stub(:save).and_return(false)
        put :update, {:id => nsfm.to_param, :nsfm => {}}, valid_session
        assigns(:nsfm).should eq(nsfm)
      end

      it "re-renders the 'edit' template" do
        nsfm = Nsfm.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Nsfm.any_instance.stub(:save).and_return(false)
        put :update, {:id => nsfm.to_param, :nsfm => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested nsfm" do
      nsfm = Nsfm.create! valid_attributes
      expect {
        delete :destroy, {:id => nsfm.to_param}, valid_session
      }.to change(Nsfm, :count).by(-1)
    end

    it "redirects to the nsfms list" do
      nsfm = Nsfm.create! valid_attributes
      delete :destroy, {:id => nsfm.to_param}, valid_session
      response.should redirect_to(nsfms_url)
    end
  end

end
