require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe NssrsController do

  # This should return the minimal set of attributes required to create a valid
  # Nssr. As you add validations to Nssr, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # NssrsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all nssrs as @nssrs" do
      nssr = Nssr.create! valid_attributes
      get :index, {}, valid_session
      assigns(:nssrs).should eq([nssr])
    end
  end

  describe "GET show" do
    it "assigns the requested nssr as @nssr" do
      nssr = Nssr.create! valid_attributes
      get :show, {:id => nssr.to_param}, valid_session
      assigns(:nssr).should eq(nssr)
    end
  end

  describe "GET new" do
    it "assigns a new nssr as @nssr" do
      get :new, {}, valid_session
      assigns(:nssr).should be_a_new(Nssr)
    end
  end

  describe "GET edit" do
    it "assigns the requested nssr as @nssr" do
      nssr = Nssr.create! valid_attributes
      get :edit, {:id => nssr.to_param}, valid_session
      assigns(:nssr).should eq(nssr)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Nssr" do
        expect {
          post :create, {:nssr => valid_attributes}, valid_session
        }.to change(Nssr, :count).by(1)
      end

      it "assigns a newly created nssr as @nssr" do
        post :create, {:nssr => valid_attributes}, valid_session
        assigns(:nssr).should be_a(Nssr)
        assigns(:nssr).should be_persisted
      end

      it "redirects to the created nssr" do
        post :create, {:nssr => valid_attributes}, valid_session
        response.should redirect_to(Nssr.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved nssr as @nssr" do
        # Trigger the behavior that occurs when invalid params are submitted
        Nssr.any_instance.stub(:save).and_return(false)
        post :create, {:nssr => {}}, valid_session
        assigns(:nssr).should be_a_new(Nssr)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Nssr.any_instance.stub(:save).and_return(false)
        post :create, {:nssr => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested nssr" do
        nssr = Nssr.create! valid_attributes
        # Assuming there are no other nssrs in the database, this
        # specifies that the Nssr created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Nssr.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => nssr.to_param, :nssr => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested nssr as @nssr" do
        nssr = Nssr.create! valid_attributes
        put :update, {:id => nssr.to_param, :nssr => valid_attributes}, valid_session
        assigns(:nssr).should eq(nssr)
      end

      it "redirects to the nssr" do
        nssr = Nssr.create! valid_attributes
        put :update, {:id => nssr.to_param, :nssr => valid_attributes}, valid_session
        response.should redirect_to(nssr)
      end
    end

    describe "with invalid params" do
      it "assigns the nssr as @nssr" do
        nssr = Nssr.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Nssr.any_instance.stub(:save).and_return(false)
        put :update, {:id => nssr.to_param, :nssr => {}}, valid_session
        assigns(:nssr).should eq(nssr)
      end

      it "re-renders the 'edit' template" do
        nssr = Nssr.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Nssr.any_instance.stub(:save).and_return(false)
        put :update, {:id => nssr.to_param, :nssr => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested nssr" do
      nssr = Nssr.create! valid_attributes
      expect {
        delete :destroy, {:id => nssr.to_param}, valid_session
      }.to change(Nssr, :count).by(-1)
    end

    it "redirects to the nssrs list" do
      nssr = Nssr.create! valid_attributes
      delete :destroy, {:id => nssr.to_param}, valid_session
      response.should redirect_to(nssrs_url)
    end
  end

end
