require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe OscfsController do

  # This should return the minimal set of attributes required to create a valid
  # Oscf. As you add validations to Oscf, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # OscfsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all oscfs as @oscfs" do
      oscf = Oscf.create! valid_attributes
      get :index, {}, valid_session
      assigns(:oscfs).should eq([oscf])
    end
  end

  describe "GET show" do
    it "assigns the requested oscf as @oscf" do
      oscf = Oscf.create! valid_attributes
      get :show, {:id => oscf.to_param}, valid_session
      assigns(:oscf).should eq(oscf)
    end
  end

  describe "GET new" do
    it "assigns a new oscf as @oscf" do
      get :new, {}, valid_session
      assigns(:oscf).should be_a_new(Oscf)
    end
  end

  describe "GET edit" do
    it "assigns the requested oscf as @oscf" do
      oscf = Oscf.create! valid_attributes
      get :edit, {:id => oscf.to_param}, valid_session
      assigns(:oscf).should eq(oscf)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Oscf" do
        expect {
          post :create, {:oscf => valid_attributes}, valid_session
        }.to change(Oscf, :count).by(1)
      end

      it "assigns a newly created oscf as @oscf" do
        post :create, {:oscf => valid_attributes}, valid_session
        assigns(:oscf).should be_a(Oscf)
        assigns(:oscf).should be_persisted
      end

      it "redirects to the created oscf" do
        post :create, {:oscf => valid_attributes}, valid_session
        response.should redirect_to(Oscf.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved oscf as @oscf" do
        # Trigger the behavior that occurs when invalid params are submitted
        Oscf.any_instance.stub(:save).and_return(false)
        post :create, {:oscf => {}}, valid_session
        assigns(:oscf).should be_a_new(Oscf)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Oscf.any_instance.stub(:save).and_return(false)
        post :create, {:oscf => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested oscf" do
        oscf = Oscf.create! valid_attributes
        # Assuming there are no other oscfs in the database, this
        # specifies that the Oscf created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Oscf.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => oscf.to_param, :oscf => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested oscf as @oscf" do
        oscf = Oscf.create! valid_attributes
        put :update, {:id => oscf.to_param, :oscf => valid_attributes}, valid_session
        assigns(:oscf).should eq(oscf)
      end

      it "redirects to the oscf" do
        oscf = Oscf.create! valid_attributes
        put :update, {:id => oscf.to_param, :oscf => valid_attributes}, valid_session
        response.should redirect_to(oscf)
      end
    end

    describe "with invalid params" do
      it "assigns the oscf as @oscf" do
        oscf = Oscf.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Oscf.any_instance.stub(:save).and_return(false)
        put :update, {:id => oscf.to_param, :oscf => {}}, valid_session
        assigns(:oscf).should eq(oscf)
      end

      it "re-renders the 'edit' template" do
        oscf = Oscf.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Oscf.any_instance.stub(:save).and_return(false)
        put :update, {:id => oscf.to_param, :oscf => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested oscf" do
      oscf = Oscf.create! valid_attributes
      expect {
        delete :destroy, {:id => oscf.to_param}, valid_session
      }.to change(Oscf, :count).by(-1)
    end

    it "redirects to the oscfs list" do
      oscf = Oscf.create! valid_attributes
      delete :destroy, {:id => oscf.to_param}, valid_session
      response.should redirect_to(oscfs_url)
    end
  end

end
